"""AUTO-GENERATED — DO NOT EDIT BY HAND.

Compiled from the YAML spec sources in this directory
(``neterse/specs/<vendor>/<family>.yaml``) by ``scripts/compile_specs.py``.
Edit the YAML, then regenerate:

    python scripts/compile_specs.py

CI fails when this module drifts from its sources
(``python scripts/compile_specs.py --check``). The YAML is the authoring
format; this generated module is what the package imports, so the runtime
keeps its zero-dependency invariant — no YAML parser at import time
(decision 27 in docs/DESIGN.md).
"""
from __future__ import annotations

import re

SPECS: list = [
    {
        'id': 'arista_eos/show_interfaces_status',
        'command': '^show\\s+int(?:erface|erfaces)?(?:\\s+\\S+)?\\s+status\\s*$',
        'platforms': 'eos|arista',
        'strategy': 'fixed_width_table',
        'keywords': ['Port', 'Name', 'Status', 'Vlan', 'Duplex', 'Speed', 'Type'],
        'header': 'port,name,status,vlan,duplex,speed,type',
        'row_match': '^(?:et|po|ma|vl|lo|tu)\\w*\\d',
        'dropped_fields': (),
        'profiles': {
            'updown': {"keep": ['port', 'status']},
        },
        'doc': 'show interfaces status (Arista EOS) -> CSV.',
    },
    {
        'id': 'arista_eos/show_ip_arp',
        'command': 'show\\s+ip\\s+arp',
        'platforms': 'eos|arista',
        'strategy': 'line_regex_table',
        'row': '^(\\d+\\.\\d+\\.\\d+\\.\\d+)\\s+([\\d:]+)\\s+([0-9a-fA-F]{4}\\.[0-9a-fA-F]{4}\\.[0-9a-fA-F]{4})\\s+(.+)$',
        'header': 'address,age,mac,interface',
        'strip_columns': [4],
        'dropped_fields': (),
    },
    {
        'id': 'arista_eos/show_vlan',
        'command': '^show\\s+vlan\\s*$',
        'platforms': 'eos|arista',
        'strategy': 'line_regex_table',
        'row': '^(\\d+)\\s+(\\S+)\\s+(active|act/unsup|sus\\S*)\\s*(.*)?$',
        'header': 'vlan,name,status,ports',
        'strip_columns': [4],
        'dropped_fields': (),
    },
    {
        'id': 'aruba_aoscx/show_interface_brief',
        'command': '^show\\s+int(?:erface|erfaces)?\\s+brief\\s*$',
        'platforms': 'aruba|aoscx|aos_cx|procurve',
        'strategy': 'fixed_width_table',
        'keywords': ['Port', 'Native', 'Mode', 'Type', 'Enabled', 'Status', 'Reason', 'Speed', 'Description'],
        'header': 'port,native_vlan,mode,type,enabled,status,reason,speed,description',
        'row_match': '^\\d+/\\d+/\\d+',
        'dropped_fields': (),
        'profiles': {
            'updown': {"keep": ['port', 'status', 'reason']},
        },
        'doc': 'show interface brief (Aruba AOS-CX) -> CSV; wrapped header and separators dropped.',
    },
    {
        'id': 'aruba_aoscx/show_vlan',
        'command': '^show\\s+vlan\\s*$',
        'platforms': 'aruba|aoscx|aos_cx|procurve',
        'strategy': 'line_regex_table',
        'row': '^(\\d+)\\s+(\\S+)\\s+(up|down)\\s+(\\S+)\\s+(\\S+)\\s*(.*)?$',
        'header': 'vlan,name,status,reason,type,interfaces',
        'strip_columns': [6],
        'dropped_fields': (),
    },
    {
        'id': 'cisco/show_cdp_lldp_neighbors',
        'command': 'show\\s+(?:cdp|lldp)\\s+neigh',
        'platforms': 'ios|xe|xr|nx',
        'strategy': 'line_regex_table',
        'row': '^(\\S+)\\s+(\\S+)\\s+\\d+\\s+(\\S.*\\S)\\s+(\\S+)\\s+(\\S+)\\s*$',
        'header': 'device,local_intf,capability,platform,remote_port',
        'strip_columns': [3],
        'unindented_rows_only': True,
        'dropped_fields': ('holdtime',),
    },
    {
        'id': 'cisco/show_interface_status',
        'command': '^show\\s+int(?:erface|erfaces)?(?:\\s+.+?)?\\s+status\\s*$',
        'platforms': 'ios|xe|nx',
        'strategy': 'fixed_width_table',
        'keywords': ['Port', 'Name', 'Status', 'Vlan', 'Duplex', 'Speed', 'Type'],
        'header': 'port,name,status,vlan,duplex,speed,type',
        'dropped_fields': (),
        'profiles': {
            'updown': {"keep": ['port', 'status']},
        },
        'doc': 'show interface status (NX-OS / Catalyst) -> CSV; drops the repeated dashed separators and per-block column headers.',
    },
    {
        'id': 'cisco/show_ip_bgp_summary',
        'command': 'show\\s+(?:ip\\s+)?bgp\\s+summary',
        'platforms': 'ios|xe|xr|nx',
        'strategy': 'line_regex_table',
        'row': '^(\\d+\\.\\d+\\.\\d+\\.\\d+)\\s+\\d+\\s+(\\d+)\\s+.*?\\s+(\\S+)\\s*$',
        'header': 'neighbor,as,state_pfxrcd',
        'dropped_fields': ('version', 'msgrcvd', 'msgsent', 'tblver', 'inq', 'outq', 'up_down'),
    },
    {
        'id': 'cisco/show_ip_eigrp_neighbors',
        'command': 'show\\s+ip\\s+eigrp\\s+neigh',
        'platforms': 'ios|xe|nx',
        'strategy': 'line_regex_table',
        'row': '^(\\d+)\\s+(\\d+\\.\\d+\\.\\d+\\.\\d+)\\s+(\\S+)\\s+(\\d+)\\s+(\\S+)\\s+(\\d+)\\s+(\\d+)\\s+(\\d+)\\s+(\\d+)',
        'header': 'h,address,interface,hold,uptime,srtt,rto,q,seq',
        'context_prefixes': ['IP-EIGRP neighbors', 'EIGRP-IPv4'],
        'dropped_fields': (),
    },
    {
        'id': 'cisco/show_ip_ospf_neighbor',
        'command': 'show\\s+ip\\s+ospf\\s+neigh',
        'platforms': 'ios|xe|xr|nx',
        'strategy': 'line_regex_table',
        'row': '^(\\d+\\.\\d+\\.\\d+\\.\\d+)\\s+(\\d+)\\s+(\\S+)\\s+(\\S+)\\s+(\\d+\\.\\d+\\.\\d+\\.\\d+)\\s+(\\S+)',
        'header': 'neighbor_id,priority,state,dead_time,address,interface',
        'dropped_fields': (),
    },
    {
        'id': 'cisco/show_ip_route',
        'command': 'show\\s+ip\\s+route',
        'platforms': 'ios|xe|xr|nx',
        'strategy': 'line_regex_table',
        'row': '^([A-Za-z*+%&][A-Za-z0-9*]{0,4}                # protocol code (C, L, S*, O, i, O*E2, ...)\n(?:\\s(?:IA|EX|E[12]|N[12]|L[12]|su|ia))?)      # two-token codes: O IA, O E2, D EX, i L1, ...\n\\s+\n(\\d+\\.\\d+\\.\\d+\\.\\d+(?:/\\d+)?)                  # prefix (mask may live on the group header)\n(?:\\s+\\[(\\d+/\\d+)\\])?                           # [admin/metric]\n(?:\\s+via\\s+(\\d+\\.\\d+\\.\\d+\\.\\d+))?             # next-hop IP, comma excluded\n(?:,\\s*\\d[\\w:.]*)*                              # route age — dropped, declared\n(?:\\s+is\\s+directly\\s+connected)?               # connected-route phrasing\n(?:,\\s*(\\S+))?                                  # egress interface\n\\s*$',
        'row_flags': re.VERBOSE,
        'header': 'proto,prefix,ad/metric,next_hop,interface',
        'dropped_fields': ('route_age', 'ecmp_alternate_paths', 'subnet_group_headers'),
        'doc': 'show ip route (IOS/IOS-XE) -> CSV; drops the Codes legend, subnet-grouping headers, route-age fields and ECMP continuation lines (all declared).',
    },
    {
        'id': 'cisco/show_version',
        'command': 'show\\s+version',
        'platforms': 'ios|xe|xr|nx',
        'strategy': 'kv_extract',
        'fields': [
            {
                'key': 'os',
                'pattern': 'Cisco\\s+(IOS|NX-OS|IOS-XE|IOS XR)\\s+Software.*Version\\s+(\\S+)',
                'flags': re.IGNORECASE,
                'template': '{1} {2}',
            },
            {
                'key': 'uptime',
                'pattern': 'uptime is\\s+(.+)',
                'flags': re.IGNORECASE,
                'strip': True,
            },
            {
                'key': 'memory',
                'pattern': '(\\d+[KMG])\\s+bytes of (?:physical\\s+)?memory',
                'flags': re.IGNORECASE,
            },
            {
                'key': 'serial',
                'pattern': '[Pp]rocessor\\s+board\\s+ID\\s+(\\S+)',
            },
            {
                'key': 'model',
                'pattern': '[Mm]odel\\s+number\\s*:\\s*(\\S+)',
            },
            {
                'key': 'image',
                'pattern': '[Ss]ystem\\s+image\\s+file\\s+is\\s+\\"([^\\"]+)\\"',
            },
        ],
        'dropped_fields': ('unmatched_lines',),
        'doc': 'show version -> one key=value line (os, uptime, memory, serial, model, image); everything unmatched is dropped.',
    },
    {
        'id': 'cisco/show_vlan_brief',
        'command': 'show\\s+vlan\\s+brief',
        'platforms': 'ios|xe|nx',
        'strategy': 'line_regex_table',
        'row': '^(\\d+)\\s+(\\S+)\\s+(active|act/unsup|sus)\\s*(.*)?$',
        'header': 'vlan,name,status,ports',
        'strip_columns': [4],
        'dropped_fields': (),
    },
    {
        'id': 'cisco_ios/show_cdp_neighbors',
        'command': 'show\\s+cdp\\s+neigh(?:bors?)?\\s*$',
        'platforms': 'ios|xe',
        'strategy': 'fixed_width_table',
        'keywords': ['Device ID', 'Local Intrfce', 'Holdtme', 'Capability', 'Platform', 'Port ID'],
        'header': 'device,local_intf,holdtime,capability,platform,remote_port',
        'row_match': '^\\S+$',
        'first_col_wraps': True,
        'dropped_fields': ('entry_count',),
        'doc': "show cdp neighbors (IOS fixed-width) -> CSV; capability legend and the derivable 'Total cdp entries' line are dropped, holdtime is kept (the legacy entry drops it).",
    },
    {
        'id': 'cisco_ios/show_ip_interface_brief',
        'command': 'show\\s+ip\\s+int(?:erface)?\\s+brief',
        'platforms': 'ios|xe|xr|nx',
        'strategy': 'line_regex_table',
        'row': '^(\\S+)\\s+(\\d+\\.\\d+\\.\\d+\\.\\d+|unassigned)\\s+(YES|NO)\\s+(\\S+)\\s+((?:administratively )?\\S+)\\s+(\\S+)',
        'header': 'interface,ip,status,protocol',
        'columns': [1, 2, 5, 6],
        'dropped_fields': ('ok', 'method'),
        'profiles': {
            'updown': {"keep": ['interface', 'status', 'protocol']},
        },
    },
    {
        'id': 'cisco_ios/show_processes_cpu_sorted',
        'command': '^show\\s+processes\\s+cpu\\s+sorted(?:\\s+\\S+)?\\s*$',
        'platforms': 'ios|xe',
        'strategy': 'line_regex_table',
        'row': '^(\\d+)\\s+(\\d+)\\s+(\\d+)\\s+(\\d+)\\s+([\\d.]+%)\\s+([\\d.]+%)\\s+([\\d.]+%)\\s+(\\d+)\\s+(.+)$',
        'header': 'pid,runtime_ms,invoked,usecs,cpu_5sec,cpu_1min,cpu_5min,tty,process',
        'strip_columns': [9],
        'context_prefixes': ['CPU utilization for five seconds:'],
        'dropped_fields': (),
        'doc': 'show processes cpu sorted (IOS/IOS-XE) -> lossless CSV; retains the aggregate utilization line and every process row.',
    },
    {
        'id': 'cisco_nxos/show_interface_brief',
        'command': '^show\\s+int(?:erface|erfaces)?(?:\\s+\\S+)?\\s+brief\\s*$',
        'platforms': 'nx',
        'strategy': 'fixed_width_table',
        'keywords': ['Ethernet', 'VLAN', 'Type', 'Mode', 'Status', 'Reason', 'Speed', 'Port'],
        'header': 'interface,vlan,type,mode,status,reason,speed,port_ch',
        'dropped_fields': (),
        'profiles': {
            'updown': {"keep": ['interface', 'status', 'reason']},
        },
        'doc': 'show interface brief (NX-OS) -> CSV; the two-line wrapped header and dashed separators are dropped.',
    },
    {
        'id': 'cisco_nxos/show_interface_status_filtered',
        'command': '^show\\s+int(?:erface|erfaces)?\\s+status\\s*\\|\\s*(?:include|exclude)\\b.*$',
        'platforms': 'nx',
        'strategy': 'line_regex_table',
        'row': '^(\\S+)\\s+(.+?)\\s+(\\S+)\\s+(\\S+)\\s+(\\S+)\\s+(\\S+)\\s+(\\S+)\\s*$',
        'header': 'port,name,status,vlan,duplex,speed,type',
        'dropped_fields': (),
    },
    {
        'id': 'juniper_junos/show_interfaces_terse',
        'command': '^show\\s+int(?:erfaces?)?\\s+terse(?:\\s+\\S+)?\\s*$',
        'platforms': 'junos|juniper',
        'strategy': 'line_regex_table',
        'row': '^(\\S+)\\s+(up|down)\\s+(up|down)(?:\\s+(\\S+))?(?:\\s+(.+))?$',
        'header': 'interface,admin,link,proto,address',
        'strip_columns': [5],
        'dropped_fields': (),
        'profiles': {
            'updown': {"keep": ['interface', 'admin', 'link']},
        },
        'doc': 'show interfaces terse (Junos) -> CSV; local+remote merge into the address column.',
    },
    {
        'id': 'juniper_junos/show_ospf_neighbor',
        'command': '^show\\s+ospf\\s+neigh(?:bor)?\\s*$',
        'platforms': 'junos|juniper',
        'strategy': 'line_regex_table',
        'row': '^(\\d+\\.\\d+\\.\\d+\\.\\d+)\\s+(\\S+)\\s+(\\S+)\\s+(\\d+\\.\\d+\\.\\d+\\.\\d+)\\s+(\\d+)\\s+(\\d+)$',
        'header': 'address,interface,state,neighbor_id,priority,dead',
        'dropped_fields': (),
    },
    {
        'id': 'mikrotik_routeros/interface_print',
        'command': '^/interface\\s+print',
        'platforms': 'mikrotik|routeros',
        'strategy': 'line_regex_table',
        'row': '^(\\d+)\\s+(?:([A-Z]{1,3})\\s+)?(\\S+)\\s+(\\S+)\\s+(\\d+)(?:\\s+(\\d+))?$',
        'header': 'num,flags,name,type,mtu,l2mtu',
        'dropped_fields': (),
    },
    {
        'id': 'mikrotik_routeros/ip_address_print',
        'command': '^/ip\\s+address\\s+print',
        'platforms': 'mikrotik|routeros',
        'strategy': 'line_regex_table',
        'row': '^(\\d+)\\s+(?:([A-Z]{1,3})\\s+)?(\\d+\\.\\d+\\.\\d+\\.\\d+/\\d+)\\s+(\\d+\\.\\d+\\.\\d+\\.\\d+)\\s+(\\S+)$',
        'header': 'num,flags,address,network,interface',
        'dropped_fields': (),
        'doc': '/ip address print (MikroTik RouterOS) -> CSV; the Flags legend line is dropped.',
    },
]
